version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - type: bind
        source: ./wordpress
        target: /var/www/html
      - type: volume
        source: php_fpm_socket
        target: /var/run/php-fpm
    restart: always

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - type: bind
        source: ./wordpress
        target: /var/www/html
      - type: volume
        source: php_fpm_socket
        target: /var/run/php-fpm
    restart: always
    depends_on:
      - app

  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT}:3306
    volumes:
      - type: volume
        source: mysql_volume
        target: /var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

volumes:
  php_fpm_socket:
  mysql_volume: